### ISSUE TITLE
Problems compiling github.com/klauspost/compress with go_repo

### ISSUE THREAD

**Issue by Tatskaari** [please-build/go-rules#113]
```
    ///third_party/go/github.com_klauspost_compress//internal/cpuinfo:_cpuinfo#abi
Error building target ///third_party/go/github.com_klauspost_compress//internal/cpuinfo:_cpuinfo#abi: exit status 1
pkg/linux_amd64/github.com/klauspost/compress/internal/cpuinfo/cpuinfo_amd64.s, line 8: #include: open /home/jpoole/please-servers/plz-out/bin/third_party/go/toolchain/pkg/include/go_asm.h: no such file or directory
```

MWE:
```python
go_repo(module="github.com/klauspost/compress", version="v1.16.5")
```

**Comment by VJftw** [comment]
Was about to open an issue for this too! Not sure if any of this helps but this is as far as I've got so far:
 1. [`go build` supposedly handles this by dynamically emitting a `go_asm.h` file](https://go.dev/doc/asm#:~:text=If%20a%20package%20has%20any%20.s%20files%2C%20then%20go%20build%20will%20direct%20the%20compiler%20to%20emit%20a%20special%20header%20called%20go_asm.h%2C)
 2. Bazel had a similar issue before: https://github.com/bazelbuild/rules_go/issues/1262 but it looks like they fixed it by adding `-asmhdr <path to create go_asm.h>` to `go tool compile`.
 3. I followed https://maori.geek.nz/how-go-build-works-750bb2ba6d8e to see what happens when building [klauspost/compress' example](https://pkg.go.dev/github.com/klauspost/compress@v1.16.5/zstd#example-ZipCompressor) (zstd requires the `cpuinfo` pkg), but it looks like the generated `go_asm.h`s are all empty anyway. So i've just done this as a really hacky workaround https://github.com/VJftw/please-go/commit/40e82a2e32718f67fcfa7e468ff70250685fa860 which seems to work.

**Comment by Tatskaari** [comment]
Yeah I remember solving this issue for go_module now. `go build` just does this:
```
go build -x github.com/klauspost/compress/internal/cpuinfo
WORK=/tmp/go-build4167323964
mkdir -p $WORK/b001/
cat >$WORK/b001/go_asm.h << 'EOF' # internal
```

`please_go install` just does `touch /home/jpoole/please-servers/plz-out/tmp/third_party/go/_zstd#a_rule._build/_work/third_party/go/zstd/internal/cpuinfo/go_asm.h`

Do you want to open a PR with the fix then?

**Comment by Tatskaari** [comment]
Ah, I can see the tools update the file:
```
cat _work/third_party/go/zstd/internal/cpuinfo/go_asm.h 
// generated by compile -asmhdr from package cpuinfo
```

I think it might emit things in that file on different platforms? Not sure. Seems like we just have to make sure the file is there though.

**Comment by Tatskaari** [comment]
Ah, I've dug a bit more and realised this is the same issue as #115. Going to close this one as I've got more info there.
